### ISSUE TITLE
Preview before registering a data resource/other resources

### ISSUE THREAD

**Issue by reetuelzajoseph** [kit-data-manager/frontend-collection#19]
**Is your feature request related to a problem? Please describe.**
Once a resource is created, if there is something seriously wrong, it cannot be easily deleted. It is better to have a separate preview and approve button before registering any resource.
https://matwerk.datamanager.kit.edu/repo-management.html

**Describe the solution you'd like**
Preview button that shows all the metadata, also the default values assigned by base-repo before finally publishing.

**Comment by ThomasJejkal** [comment]
Do you have any example for something going "seriously wrong"? If there is a typo or missing, optional metadata somewhere, this can be fixed later. Besides of that, I cannot imagine any serious error. 

But you are right, removing DataResources is not part of the UI, which is intentional. To remove a DataResource from public access, you may update the DataResource and set its state to "REVOKED", which hides the resource for everybody but the owner and site administrators. Deleting the DataResource is then something that should happen in the backend if this is really desired.

**Comment by ThomasJejkal** [comment]
As far as I know there are no default values which are not visible in the form before saving. The only "default values" are used if you add an array element which contains a controlled list represented as combo box (see #15).

**Comment by reetuelzajoseph** [comment]
if no access data is available, access would be set to anonymousUser. Also I think creators and identifiers are assigned by default when not entered specifically(base-repo)

**Comment by ThomasJejkal** [comment]
I see, but these are defaults added by the base-repo to assign default ownership and creator information. Basically, it uses the caller to determine these information. The frontend is not aware of these values.
In any case, one should check whether creating resources without login is something that is desired and I have to check if there is a way for disallow such operations if authentication is enabled.
