### ISSUE TITLE
What does clicking Validate button actually do?

### ISSUE THREAD

**Issue by reetuelzajoseph** [kit-data-manager/frontend-collection#23]
**Describe the bug**
Clicking Validate seems to only check if the fields are empty or not..

**To Reproduce**
1. Go to https://matwerk.datamanager.kit.edu/metadata-management.html
2. Fill the form
3. Click on  Validate
4. Everything becomes green, even though no metadata document is uploaded

**Expected behavior**
If it is a URL, it should check if it is actually a URL. If there is no metadata document added, it should say that there is no metadata document added instead of adding a blank document.

**Shouldn't it also check if the uploaded metadata document follows the Schema selected??**

**Screenshots**
![image](https://github.com/kit-data-manager/frontend-collection/assets/88380730/d30533f2-1a72-45a1-bdf6-d421aafc4a3b)

**Comment by ThomasJejkal** [comment]
The 'Validate" button only validated the form inputs (in that case Record Metadata) against the schema definition this form was created from. Regarding "Related Resource Identifier" and "Related Resource Identifier Type", even if there is a semantic relationship between both of them, the metadata schema does not reflect this kind of relationship such that only the backend service, i.e., MetaStore, can check such constraints. For the schema, these are two attributes, one of type string, the other of type enum. More complex validations are not in the scope of the underlying library.  

Furthermore, in that case, it only related to the Record Metadata itself and ensures, that all mandatory elements of Record Metadata are provided in order to allow to also provide a Metadata Document (which is the second tab that is enabled as soon as Record Metadata has been validated). The Metadata Document itself is not validated in frontend-collection as this is done by MetaStore at ingest time. Currently, I'm not sure what happens if this validation fails. Probably, the modal dialog will close and an error will be logged. Here it might be possible, to add a validation step after clicking "Submit" to keep the dialog open also in case of an error, which is something that can be included in the next version.

**Comment by reetuelzajoseph** [comment]
![image](https://github.com/kit-data-manager/frontend-collection/assets/88380730/fb306603-124b-45ad-afa5-43d627d4e04b)

I just saw that while clicking Submit if the metadata does not match the Schema, the above dialog box appears. I would prefer to have it when I click validate itself. So real metadata document validation happens on clicking the Submit button.

**Comment by ThomasJejkal** [comment]
Ok, good to know. Validating both, record and document, by clicking "Validate" will not be possible according to the workflow I described before, because according to that it is totally legit to have a valid record but no document yet, whereas if you add a document manually, the user does not see the "Validate" button any longer. Reflecting all options in this single button may cause more confusion than it solves I guess.

**Comment by ThomasJejkal** [comment]
Closed because "working as intended".
